Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations like:
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements 
c) Divide every element by 2 

In [1]:
import numpy as np
a=np.array([11,22,33,44,55])

print('Array + 2 : ',a+2)
print('Array * 3 : ',a*3)
print('Array / 2 : ',a/2)

Array + 2 :  [13 24 35 46 57]
Array * 3 :  [ 33  66  99 132 165]
Array / 2 :  [ 5.5 11.  16.5 22.  27.5]


Q.2 Questions on Basic NumPy Array: 
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
b) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [2]:
import numpy as np
arr=np.array([1,2,3,6,4,5])

rev=arr[::-1]     
# we can use flip function too i.e. rev=np.flip(arr) 
print('Reversed:',rev)


x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

max_x=np.bincount(x).argmax()
max_y=np.bincount(y).argmax()

indices_x=np.where(x==max_x)[0]
indices_y=np.where(y==max_y)[0]
print('In X:')
print('Most Frequent: ',max_x)
print('Indices: ',indices_x)
print()
print('In Y:')
print('Most Frequent: ',max_y)
print('Indices: ',indices_y)

Reversed: [5 4 6 3 2 1]
In X:
Most Frequent:  1
Indices:  [0 5 7 8 9]

In Y:
Most Frequent:  1
Indices:  [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows: 
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

In [5]:
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])

print(arr[0][1])
print(arr[2][0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute? 

In [4]:
import numpy as np
jitesh_maurya=np.linspace(10,100,25)

print('Array:',jitesh_maurya)


print('Dimension: ',jitesh_maurya.ndim)
print('Shape :',jitesh_maurya.shape)
print('Number of elements:',jitesh_maurya.size)
print('Data Type:',jitesh_maurya.dtype)
print('Total bytes: ',jitesh_maurya.nbytes)

jitesh_maurya_transpose=jitesh_maurya.reshape(25,1)
print('Using reshape:')
print(jitesh_maurya_transpose)

print('Using T:')
t=jitesh_maurya.T
print(t)

print('T cannot be performed on 1D array')

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension:  1
Shape : (25,)
Number of elements: 25
Data Type: float64
Total bytes:  200
Using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
T cannot be performed on 1D array


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<your_name>>.

In [3]:
import numpy as np
ucs420_jiteshmaurya=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_jiteshmaurya)
print('Mean : ',np.mean(ucs420_jiteshmaurya))
print('Median : ',np.median(ucs420_jiteshmaurya))
print('Max : ',np.max(ucs420_jiteshmaurya))
print('Min : ',np.min(ucs420_jiteshmaurya))
print('Unique elements: ',np.unique(ucs420_jiteshmaurya))
print()

#Reshape
reshaped_ucs420_jiteshmaurya=ucs420_jiteshmaurya.reshape(4,3)
resized_ucs420_jiteshmaurya=np.resize(ucs420_jiteshmaurya,(2,3))
print('Reshaped:')
print(reshaped_ucs420_jiteshmaurya)
print()

print('Resized:')
print(resized_ucs420_jiteshmaurya)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean :  43.333333333333336
Median :  37.5
Max :  90
Min :  10
Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]

Reshaped:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized:
[[10 20 30]
 [40 50 60]]
